server:
  port: 9095

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: myuser
      password: 123456
      database: ubank

feign:
  schat:
    url: http://localhost:9090
